---
title: 'Acesso negado entre os órgãos'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_depth: 4
    theme: paper
    df_print: default
runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = T,
  comment = "#>",
  message = F,
  warning = F,
  echo = T,
  fig.width = 8,
  fig.height = 5
)
```

```{r libs}
library(tidyverse)
library(lubridate)
library(glue)
library(here)
library(ggtext)
library(patchwork)
library(kableExtra)
library(hrbrthemes)
library(tidytext)
```

```{r set-options}
set.seed(1014)

knitr::knit_hooks$set(inline = function(x) prettyNum(x, big.mark = ".", decimal.mark = ","))

options(
  digits = 1,
  scipen = 999,
  OutDec = ",",
  knitr.kable.NA = "",
  radian.auto_match = FALSE
)

Sys.setenv(LANGUAGE = "pt-br")

# helper
`%notin%` <- function(x, y) !(x %in% y)
```

```{r color-settings}
# aplica identidade visual da TB/AeP:
cores_aep <- c(
  laranja = "#F9A521",
  rosa = "#D81755",
  cinza = "#969696",
  marrom = "#B27D5C"
)

cores_tb <- c(
  laranja = "#F6A323",
  cinza_escuro = "#1d1d1b",
  cinza_claro = "#6f7171",
  cinza_quase_branco = "#ececec",
  azul = "#41ACBD"
)

cores_decisao <- c(
  "Acesso Concedido" = cores_tb[["azul"]],
  "Não se trata de solicitação de informação" = cores_aep[["marrom"]],
  "Acesso Negado" = cores_aep[["rosa"]],
  "Acesso Parcialmente Concedido" = cores_aep[["laranja"]],
  "Pergunta Duplicada/Repetida" = cores_aep[["cinza"]],
  "Órgão não tem competência para responder sobre o assunto" = cores_tb[["cinza_escuro"]],
  "Informação Inexistente" = cores_tb[["cinza_quase_branco"]]
  )

cores_decisao2 <- cores_decisao
cores_decisao2[["Informação Inexistente"]] <- "gray20"

cores_decisao3 <- c("black", "gray90", "gray20", "gray80", "gray20")
names(cores_decisao3) <- names(cores_decisao)[-c(5, 2)] 

cores_lai <- tibble(
  c1 = c("Não se trata de solicitação de informação",
         "Pergunta Duplicada/Repetida",
         "Pedidos de acesso a informação via LAI"
         ) %>% str_wrap(25),
  c2 = c("#F9A521", "#969696", "#D81755")
) %>% deframe()
```

```{r}
pedidos_painel <- "dados/load/rds/base_cgu.rds" %>%
  here() %>%
  readRDS() %>%
  pluck("pedidos") %>%
  janitor::clean_names() %>% 
  mutate(
    ts_registro = data_registro,
    ts_resposta = data_resposta,
    data_registro = dmy(data_registro) %>% floor_date(unit = "month"),
    data_resposta = dmy(data_resposta) %>% floor_date(unit = "month")) %>% 
  rename(orgao = orgao_destinatario) %>%
  filter(!is.na(decisao), !is.na(data_resposta), data_registro < ymd("2021-10-01"))
```

```{r}
taxas <- pedidos_painel %>%
  filter(decisao %notin% c(
    "Pergunta Duplicada/Repetida",
    "Não se trata de solicitação de informação"
  )) %>% 
  mutate(orgao = str_wrap(orgao, 40)) %>% 
  select(id_pedido, data_registro, decisao, orgao) %>% 
  add_count(data_registro, name = "n_mes") %>% 
  add_count(data_registro, orgao, name = "n_mes_orgao") %>% 
  filter(decisao == "Acesso Negado") %>% 
  add_count(data_registro, decisao, name = "n_mes_acesso_negado") %>% 
  add_count(data_registro, decisao, orgao, name = "n_mes_acesso_negado_orgao") 

taxas_smry <- taxas %>% 
  select(-id_pedido) %>% 
  distinct() %>% 
  group_by(data_registro, orgao) %>% 
  summarise(across(starts_with("n_mes"), sum), .groups = "drop") %>% 
  mutate(
    taxa_de_negativa_orgao = n_mes_acesso_negado_orgao / n_mes_orgao,
    taxa_de_negativa_relativa = n_mes_acesso_negado_orgao / n_mes_acesso_negado
  )
```

```{r fig.height=8, fig.width=10}
taxas_smry %>% 
  group_by(data_registro) %>% 
  arrange(data_registro, -taxa_de_negativa_relativa) %>% 
  mutate(ord = 1:n()) %>% 
  filter(ord < 2) %>% 
  group_by(data_registro, orgao) %>% 
  summarise(taxa_de_negativa_relativa = sum(taxa_de_negativa_relativa),
            .groups = "drop") %>% 
  mutate(mes = month.abb[month(data_registro)],
         data_registro = data_registro) %>%
  ggplot(aes(x = data_registro, y = taxa_de_negativa_relativa, color = orgao)) +
  geom_segment(aes(y = 0, yend = taxa_de_negativa_relativa,
                   x = data_registro , xend = data_registro), color = "gray60") +
  geom_vline(xintercept = seq(ymd('2012-01-01'), ymd('2022-01-01'), by = 'year'), lty = 3) +
  scale_y_percent(limits = c(0, 0.7)) +
  scale_x_date(
    limits = c(ymd("2012-01-01"), ymd("2022-01-01")),
    breaks = scales::date_breaks("6 months"),
    date_labels = "%b") +
  geom_point(size = 4, alpha = .6) +
  geom_text(
    aes(label = str_extract(orgao, "^[:upper:]+(?= )|^GSI-PR"),
        y = taxa_de_negativa_relativa),
    size = 2.5,
    angle = 90,
    fontface = "bold",
    color = "black",
    hjust = 0,
    check_overlap = T) +
  # geom_text(aes(label = if_else(month(data_resposta) %in% c(1,3,6,9), mes, ""),
  #               y = 0.01), size = 2.5, color = "gray20") +
  geom_text(
    data = . %>% filter(month(data_registro) == 2) %>% 
      add_row(data_registro = ymd("2012-02-01"), mes = "Feb"),
    aes(label = year(data_registro), y = .015),
    size = 3.5,
    # vjust = 1.3,
    hjust = .15,
    color = "gray20",
    fontface = "bold",
    show.legend = F
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 9, margin = margin(5, 0, 5, 0, "pt")),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 9),
    strip.text = element_text(size = 12),
    plot.title = element_text(size = 14)
  ) +
  guides(color = guide_legend(ncol = 2, title.position = "top")) +
  labs(
    title = "Órgãos que mais negaram acesso a informação por mês",
    subtitle = "Como % do total de pedidos negados no FalaBr",
    color = "Sigla do órgão:",
    x = NULL,
    y = "% do total de acessos negados\nentre todos os pedidos no FalaBr"
  )
```

```{r}
pedidos_painel %>% 
  count(ano = year(data_registro), orgao) %>% 
  count(ano) %>% 
  ggplot(aes(x = as.character(ano), y = n)) +
  geom_col(fill = cores_aep[["marrom"]]) +
  geom_hline(aes(yintercept = n_distinct(pedidos_painel$orgao))) +
  geom_text(
    aes(
      y = n_distinct(pedidos_painel$orgao) + 10,
      x = "2016",
      label = glue("Total de órgãos no Executivo Federal: {n_distinct(pedidos_painel$orgao)}")
    ),
    check_overlap = T
  ) +
  geom_text(aes(label = n), vjust = 1, fontface = "bold", size = 5) +
  theme_minimal() +
  labs(
    x = "Ano",
    y = "Quantidade de órgãos",
    title = "Número de órgãos requisitados nos pedidos de acesso a informação"
  )
```

A maioria das negativas de acesso a informação eram concentradas em poucos órgãos:

```{r}
taxas_smry %>% 
  group_by(ano = year(data_registro), orgao) %>% 
  summarise(
    n_ano = sum(n_mes),
    n_ano_orgao = sum(n_mes_orgao),
    n_ano_acesso_negado = sum(n_mes_acesso_negado),
    n_ano_acesso_negado_orgao = sum(n_mes_acesso_negado_orgao)
  ) %>% 
  mutate(per = n_ano_acesso_negado_orgao / n_ano_acesso_negado) %>% 
  arrange(ano, -per) %>% 
  mutate(per_ac = cumsum(per), ord = row_number()) %>% 
  filter(ord == 5) %>% 
  ggplot(aes(x = ano, y = per_ac)) +
  geom_line(color = cores_aep[["marrom"]], size = 1) +
  geom_point(color = cores_aep[["marrom"]]) +
  theme_minimal() +
  hrbrthemes::scale_y_percent() +
  labs(
    title = "Participação dos 5 órgãos que mais negaram acesso a informação",
    subtitle = "Como % do total de acessos negados no ano",
    y = NULL,
    x = NULL
  )
```

```{r}
library(shiny)
library(shinyWidgets)
library(plotly)
choices <- sort(readRDS(here(glue("cgu-interact/data/select_orgao.rds"))))

shinyApp(

  ui = fluidPage(
    selectizeInput(
      inputId = "select_orgao",
      label = "Digite o nome ou selecione um órgão",
      choices = choices,
      options = list(
        placeholder = "Digite/selecione um órgão",
        onInitialize = I('function() { this.setValue(""); }')
      )),
    sliderTextInput(
      inputId = "date_range",
      label = "Selecione um intervalo de tempo:",
      choices = seq.Date(ymd("2012-05-01"), ymd("2021-12-01"), by = "month"),
      selected = c(ymd("2012-05-01"), ymd("2021-12-01"))
    ),
    h4("Acessos negados em relação ao total de negativas no FalaBr"),
    textOutput(outputId = "data_inicio"),
    textOutput(outputId = "value"),
              plotlyOutput(
                outputId = "acesso_negado_global",
                width = "1000px",
                height = "400px"
              )
  ),
  
  server = function(input, output) {
    
    output$value <- renderPrint({
      validate(need(input$select_orgao, ""))
      glue("Órgão: {input$select_orgao}")
    })
          
    my_date_fmt <- function(x) format(as.Date(x), format = "%b.%Y")
    dt_ini <- reactive({
      glue("Período: {my_date_fmt(input$date_range[1])} até {my_date_fmt(input$date_range[2])}")
    })
      
    output$data_inicio <- renderPrint({dt_ini()})
    
    acesso_negado <- reactive({
      taxas_smry %>%
        filter(between(data_registro, ymd(input$date_range[1]), ymd(input$date_range[2])))
    })
    
    output$acesso_negado_global  <- renderPlotly({
        validate(need(input$select_orgao, "Selecione um órgão"))
    
        my_plot <- acesso_negado() %>% 
        filter(orgao == input$select_orgao) %>%
        ggplot(aes(
          x = data_registro, 
          y = taxa_de_negativa_relativa,
          fill = "Acesso Negado",
          text = glue("{orgao} - {data_registro}<br>Total pedidos do órgão: {n_mes_orgao}<br>Total pedidos do órgão com Acesso Negado: {n_mes_acesso_negado_orgao}<br>Total de pedidos com Acesso negado no FalaBr: {n_mes_acesso_negado}")
        )) +
        geom_col(show.legend = F) +
        scale_fill_manual(values = cores_decisao[["Acesso Negado"]]) +
        geom_point() +
        theme_minimal() +
        labs(
          y = "% em relação ao total\nde acessos negados no FalaBr",
          x = NULL
        )
    
        ggplotly(my_plot, tooltip = "text", dynamicTicks = T) %>% 
          layout(
            yaxis = list(tickformat = '%', range = c(0, 100)), 
            showlegend = F
          )

    })
      
  },

  options = list(height = 500)
)
```

