---
title: 'Negativas de acesso a informação no governo Federal'
subtitle: 'Mapeamento e contagem de pedidos com detecção de termo LGPD nas interações'
output:
  html_document: 
    code_folding: hide
    toc: no
    theme: paper
    df_print: default
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = T,
  comment = "#>",
  message = F,
  warning = F,
  echo = T,
  fig.width = 8,
  fig.height = 5
)
```

```{r set-options}
set.seed(1014)

knitr::knit_hooks$set(inline = function(x) prettyNum(x, big.mark = ".", decimal.mark = ","))

options(
  digits = 1,
  scipen = 999,
  OutDec = ",",
  knitr.kable.NA = "",
  radian.auto_match = FALSE
)

Sys.setenv(LANGUAGE = "pt-br")
Sys.setlocale("LC_TIME", "pt_BR")
```

```{r libs}
library(tidyverse)
library(lubridate)
library(here)
`%notin%` <- function(x, y) !(x %in% y)
```

```{r color-settings}
source(here("src/0-paleta-de-cores.R"), encoding = "UTF-8")

theme_set(theme_minimal())

theme_update(
  panel.grid.minor = element_blank(),
  panel.background = element_rect(fill = "gray97", color = "transparent")
)
```

```{r}
pedidos_cgu <- "dados/load/rds/pedidos-cgu.rds" %>% 
  here() %>% 
  readRDS() %>%
  rename(orgao = orgaodestinatario) %>% 
  filter(decisao %notin% c(
    "Pergunta Duplicada/Repetida",
    "Não se trata de solicitação de informação"
  ))

recursos_cgu <- "dados/load/rds/recursos-cgu.rds" %>% 
  here() %>% 
  readRDS() %>%
  rename(orgao = orgaodestinatario) %>% 
  distinct() %>% 
  group_by(id_pedido) %>% 
  filter(row_number() == 1) %>% 
  ungroup()

pedidos_clean <- "dados/load/rds/pedidos-clean.rds" %>% 
  here() %>% 
  readRDS() 

recursos_clean <- "dados/load/rds/recursos-clean.rds" %>% 
  here() %>% 
  readRDS() %>% 
  distinct() %>% 
  group_by(id_pedido) %>% 
  filter(row_number() == 1) %>% 
  ungroup()
```

```{r  fig.height=8, fig.width=10}
pedidos_clean <- pedidos_clean %>% 
  mutate(
    usa_lgpd_pedido_resumido = str_detect(resumo_solicitacao_clean, "LGPD"),
    usa_lgpd_pedido = str_detect(detalhamento_solicitacao_clean, "LGPD"),
    usa_lgpd_resposta = str_detect(resposta_clean, "LGPD")
  )

recursos_clean <- recursos_clean %>% 
  mutate(
    usa_lgpd_recurso = str_detect(desc_recurso_clean, "LGPD"),
    usa_lgpd_resposta_recurso = str_detect(resposta_recurso_clean, "LGPD"),
    usa_lgpd = usa_lgpd_recurso | usa_lgpd_resposta_recurso
  )

lgpd <- pedidos_cgu %>% 
  select(
    id_pedido, orgao, data_registro,
    resumo_solicitacao, detalhamento_solicitacao, 
    resposta, decisao, assunto_pedido
  ) %>% 
  left_join(pedidos_clean) %>%
  mutate(
    usa_lgpd_assunto = assunto_pedido == "Dados Pessoais - LGPD",
    usa_lgpd_pedido_resumido = replace_na(usa_lgpd_pedido_resumido, FALSE),
    usa_lgpd = !(
      !usa_lgpd_pedido_resumido & 
      !usa_lgpd_pedido &
      !usa_lgpd_resposta & 
      !usa_lgpd_assunto
  ))
```

#### Detectando termos relacionados a LGPD

Foi realizada uma busca no pedido, no resumo do pedido, na resposta, nos recursos e nas respostas dos recursos. A busca foi feita com a regex:

- `"lei geral de protecao de dados|lei de protecao de dados pessoais|lgpd|13709|13 709"`

Também foi detectado na base de dados a nomenclatura **Dados pessoais - LGPD** no campo de assunto do pedido.

```{r fig.height=12, fig.width=10}
ord_interacao <- ordered(c(
   "usa_lgpd",
   "usa_lgpd_assunto",
   "usa_lgpd_pedido_resumido",
   "usa_lgpd_pedido",
   "usa_lgpd_resposta",
   "usa_lgpd_recurso_primeira_instancia",
   "usa_lgpd_resposta_recurso_primeira_instancia",
   "usa_lgpd_recurso_segunda_instancia",
   "usa_lgpd_resposta_recurso_segunda_instancia",
   "usa_lgpd_recurso_cgu",
   "usa_lgpd_resposta_recurso_cgu",
   "usa_lgpd_recurso_cmri",
   "usa_lgpd_resposta_recurso_cmri",
   "usa_lgpd_revisao",
   "usa_lgpd_resposta_revisao"
))

recursos_clean_instancias <- recursos_clean %>% 
  select(starts_with("id"), where(is.logical)) %>% 
  left_join(
    recursos_cgu %>% 
      select(id_pedido, id_recurso, instancia)
  ) %>% 
  select(-id_recurso)

recs <- recursos_clean_instancias %>% 
  mutate(instancia = if_else(instancia == "Terceira Instância", "CGU", instancia)) %>% 
  group_by(instancia) %>% 
  nest() %>% 
  ungroup() %>% 
  deframe()

recs$`Primeira Instância` <- recs$`Primeira Instância` %>% 
  rename(
    usa_lgpd_recurso_primeira_instancia = usa_lgpd_recurso,
    usa_lgpd_resposta_recurso_primeira_instancia = usa_lgpd_resposta_recurso
  ) %>%
  select(-usa_lgpd)

recs$`Segunda Instância` <- recs$`Segunda Instância` %>% 
  rename(
    usa_lgpd_recurso_segunda_instancia = usa_lgpd_recurso,
    usa_lgpd_resposta_recurso_segunda_instancia = usa_lgpd_resposta_recurso
  ) %>%
  select(-usa_lgpd)

recs$`CGU` <- recs$`CGU` %>% 
  rename(
    usa_lgpd_recurso_cgu = usa_lgpd_recurso,
    usa_lgpd_resposta_recurso_cgu = usa_lgpd_resposta_recurso
  ) %>%
  select(-usa_lgpd)

recs$`CMRI` <- recs$`CMRI` %>% 
  rename(
    usa_lgpd_recurso_cmri = usa_lgpd_recurso,
    usa_lgpd_resposta_recurso_cmri = usa_lgpd_resposta_recurso
  ) %>%
  select(-usa_lgpd)

recs$`Pedido de Revisão` <- recs$`Pedido de Revisão` %>% 
  rename(
    usa_lgpd_revisao = usa_lgpd_recurso,
    usa_lgpd_resposta_revisao = usa_lgpd_resposta_recurso
  ) %>%
  select(-usa_lgpd)


lbl_x <- c("Assunto", "Resumo do\npedido", 
           "Pedido", "Resposta", "Reclamação", "Resposta\nreclamação",
           "Recurso 1ª", "Resposta\nrecurso 1ª", "Recurso 2ª", 
           "Resposta\nrecurso 2ª", "CGU", "Resposta\nCGU 3ª",
           "CMRI", "Resposta\nCMRI")

cores_detecta_lgpd <- c(
  "Termo LGPD não detectado" = cores_aep[["laranja"]],
  "Termo LGPD detectado" = cores_aep[["rosa"]]
)

recs %>%  
  reduce(full_join) %>% 
  left_join(lgpd, .) %>% 
  select(id_pedido, where(is.logical)) %>% 
  count(
    usa_lgpd,
    usa_lgpd_assunto,
    usa_lgpd_pedido_resumido,
    usa_lgpd_pedido,
    usa_lgpd_resposta,
    usa_lgpd_recurso_primeira_instancia,
    usa_lgpd_resposta_recurso_primeira_instancia,
    usa_lgpd_recurso_segunda_instancia,
    usa_lgpd_resposta_recurso_segunda_instancia,
    usa_lgpd_recurso_cgu,
    usa_lgpd_resposta_recurso_cgu,
    usa_lgpd_recurso_cmri,
    usa_lgpd_resposta_recurso_cmri,
    usa_lgpd_revisao,
    usa_lgpd_resposta_revisao,
    sort = T
  ) %>% 
  mutate(combinacao = str_glue("Combinação {row_number()}")) %>% 
  pivot_longer(
    -c(n, combinacao),
    names_to = "onde",
    values_to = "usa"
  ) %>% 
  filter(!is.na(usa), onde != "usa_lgpd") %>% 
  mutate(onde = ordered(onde, levels = ord_interacao),
         usa = case_when(
           usa ~ "Termo LGPD detectado",
           !usa ~ "Termo LGPD não detectado"
  )) %>% 
  ggplot(aes(
    x = onde,
    y = reorder(combinacao, n),
    fill = usa,
    group = reorder(combinacao, n)
  )) +
  geom_line() +
  geom_point(color = "transparent", shape = 21, size = 4) +
  geom_text(
    data = . %>% filter(onde == "usa_lgpd_assunto"),
    aes(label = n),
    hjust = 1,
    check_overlap = T
  ) +
  scale_x_discrete(labels = lbl_x, position = "top") +
  scale_fill_manual(values = cores_detecta_lgpd) +
  labs(
    title = "Mapeamento do pedido do início ao fim",
    subtitle = str_glue(
      "Cada ponto é uma interação registrada,",
      "o texto da interação foi analizado detectando",
      "ou não termos associados a LGPD"
    ),
    fill = NULL,
    x = NULL,
    y = NULL
  ) +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank()
  )
```