---
title: 'Recursos'
subtitle: 'Órgãos e entidades do poder Executivo'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_depth: 4
    theme: paper
    df_print: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = T,
  comment = "#>",
  message = F,
  warning = F,
  echo = T,
  fig.width = 8,
  fig.height = 5
)
```

```{r libs}
library(tidyverse)
library(lubridate)
library(glue)
library(here)
library(ggtext)
library(patchwork)
library(kableExtra)
library(hrbrthemes)
library(tidytext)
```

```{r set-options}
set.seed(1014)

knitr::knit_hooks$set(
  inline = function(x) prettyNum(x, big.mark = ".", decimal.mark = ",")
  )

options(
  digits = 1,
  scipen = 999,
  OutDec = ",",
  knitr.kable.NA = "",
  radian.auto_match = FALSE
)

Sys.setenv(LANGUAGE = "pt-br")

# helper
`%notin%` <- function(x, y) !(x %in% y)
```

```{r color-settings}
source(here("src/0-paleta-de-cores.R"),encoding = "UTF-8")

theme_set(theme_minimal())

theme_update(
  panel.grid.minor = element_blank(),
  panel.background = element_rect(fill = "gray97", color = "transparent")
)
```

```{r}
#' base de dados de pedidos - completa
pedidos_painel <- "dados/load/rds/base-cgu.rds" %>%
  here() %>%
  readRDS() %>%
  pluck("pedidos") %>%
  janitor::clean_names() %>% 
  mutate(
    ts_registro = data_registro,
    ts_resposta = data_resposta,
    data_registro = dmy(data_registro) %>% floor_date(unit = "month"),
    data_resposta = dmy(data_resposta) %>% floor_date(unit = "month")) %>% 
  rename(orgao = orgao_destinatario) %>%
  filter(!is.na(decisao),
         !is.na(data_resposta),
         data_registro < ymd("2021-10-01"), 
         esfera == "Federal")

#' base de dados de recursos - completa
recursos_painel <- "dados/load/rds/base-cgu.rds" %>%
  here() %>%
  readRDS() %>%
  pluck("recursos_reclamacoes") %>%
  janitor::clean_names() %>% 
  mutate(
    ts_registro = data_registro,
    ts_resposta = data_resposta,
    data_registro = dmy(data_registro) %>% floor_date(unit = "month"),
    data_resposta = dmy(data_resposta) %>% floor_date(unit = "month")) %>% 
  rename(orgao = orgao_destinatario) %>%
  filter(!is.na(instancia),
         !is.na(data_resposta),
         data_registro < ymd("2021-10-01"), 
         esfera == "Federal")
```


```{r}
# filtra pedidos com recursos, na instância recursal em que ele finalizou:
recursos_por_id_instancia_e_decisao <- recursos_painel %>% 
  filter(instancia != "Pedido de Revisão") %>% 
  group_by(id_pedido) %>%
  arrange(id_pedido, instancia) %>% 
  mutate(ord = 1:n()) %>% # ordenação por instancia recursal
  select(id_pedido, instancia, data_registro_recurso = data_registro, ord) %>% 
  ungroup()

count_recursos_total <- recursos_por_id_instancia_e_decisao %>%
  group_by(id_pedido) %>% 
  filter(ord == max(ord)) %>% 
  left_join(
    select(pedidos_painel, 
           id_pedido, data_registro_pedido = data_registro, decisao), 
    .) %>% 
  mutate(instancia = fct_expand(instancia, "Não houve recurso"),
         instancia = replace_na(instancia, "Não houve recurso")) %>% 
  mutate(ano = year(data_registro_pedido)) %>% 
  count(ano, instancia, decisao,
        name = "n_recursos_ano_instancia_e_decisao")  %>% 
  mutate(houve_recurso = instancia == "Não houve recurso") %>%  
  count(ano, houve_recurso,
        wt = n_recursos_ano_instancia_e_decisao,
        name = "n_ano_houve_recurso") %>% 
  add_count(ano,
            wt = n_ano_houve_recurso,
            name = "n_ano") %>% 
  mutate(per = n_ano_houve_recurso / n_ano) 
```

```{r fig.height=3}
my_lbl <- function(x) scales::percent(x, accuracy = 0.01, decimal.mark = ",")

count_recursos_total %>% 
  ggplot(aes(x = ano, y = per, group = houve_recurso, color = houve_recurso)) +
  geom_text(data = . %>% filter(houve_recurso), show.legend = F,
            aes(label = my_lbl(per)), nudge_y = -.1, check_overlap = T) +
  geom_text(data = . %>% filter(!houve_recurso), show.legend = F,
            aes(label = my_lbl(per)), nudge_y = .1, check_overlap = T) +
  geom_line(size = 1.2, color = "gray30") +
  geom_point(size = 2.5) +
  scale_fill_manual(values = c(cores_aep[["rosa"]], cores_tb[["azul"]]),
                     labels = c("Não houve recurso", "Houve recurso*"),
                     name = "% do total de pedidos"
                     ) +
  scale_color_manual(values = c(cores_aep[["rosa"]], cores_tb[["azul"]]),
                     labels = c("Não houve recurso", "Houve recurso*"),
                     name = "% do total de pedidos"
                     ) +
  scale_x_continuous(breaks = 2012:2021) + 
  guides(colour = guide_legend(reverse = T)) +
  hrbrthemes::scale_y_percent(decimal.mark = ",") +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank()) +
  labs(title = "Pedidos que entraram com recurso",
       subtitle = "% do total de pedidos que entraram com recurso",
       x = NULL, y = NULL, caption = "*Pelo menos um recurso em 1ª instância")
```

```{r}
count_recursos_total %>% 
  ggplot(aes(x = ano, y = n_ano_houve_recurso,
             fill = reorder(houve_recurso, -per))) +
  geom_col() +
  scale_fill_manual(
    values = c(cores_tb[["azul"]], cores_aep[["rosa"]]),
    labels = c("Não houve recurso", "Houve recurso*"),
    name = "% do total de pedidos"
  ) +
  scale_x_continuous(breaks = 2012:2021) + 
  #guides(fill = guide_legend(reverse = T)) +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank()) +
  labs(title = "Total de pedidos que entraram com recurso",
       x = NULL, y = NULL, caption = "*Pelo menos um recurso em 1ª instância")
```


Somente pedidos com recursos:

```{r fig.height=3}
count_recursos_total %>%
  filter(!houve_recurso) %>% 
  ggplot(aes(x = ano, y = per, group = houve_recurso, color = houve_recurso)) +
  geom_text(data = . %>% filter(houve_recurso), show.legend = F,
            aes(label = my_lbl(per)), nudge_y = -.1, check_overlap = T) +
  geom_line(size = 1.3, color = "gray30") +
  geom_point(size = 2.3, color = cores_aep[["rosa"]]) +
  scale_x_continuous(breaks = 2012:2021) + 
  guides(colour = guide_legend(reverse = T)) +
  hrbrthemes::scale_y_percent(decimal.mark = ",", accuracy = 0.1, limits = c(0.06, .1)) +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank()) +
  labs(title = "Pedidos que entraram com recurso",
       subtitle = "% do total de pedidos que entraram com recurso",
       x = NULL, y = NULL, caption = "*Pelo menos um recurso em 1ª instância")
```


```{r}
depara_orgao <- pedidos_painel %>%
  select(id_pedido, orgao, decisao)

inst <- c(
  "Primeira Instância",
  "Segunda Instância",
  "CGU",
  "CMRI",
  "Pedido de Revisão"
)
```

```{r}
#' 1015 recursos com tipo_recurso="Não concorda com a transformação do pedido em manifestação" e resposta indeferida.
#' Não é possível saber a origem desses pedidos nem o órgão.
recursos_painel %>% 
  filter(!id_pedido %in% depara_orgao$id_pedido) %>% count(tipo_recurso, orgao,tipo_resposta )
```

```{r}
count_recursos <- recursos_painel %>% 
  transmute(
    id_pedido,
    id_recurso,
    instancia = factor(instancia, levels = inst),
    orgao
  ) %>% 
  arrange(id_pedido, instancia) %>%
  group_by(id_pedido) %>% 
  mutate(
    ord = row_number(),
    orgao_old = orgao,
  ) %>%
  ungroup() %>%  
  select(-orgao) %>% 
  group_by(id_pedido) %>% 
  filter(ord == max(ord)) %>% 
  ungroup() %>%
  filter(id_pedido %in% depara_orgao$id_pedido) %>% 
  left_join(depara_orgao, .) %>% 
  select(id_pedido:decisao, instancia) %>% 
  count(orgao, decisao, instancia,
        name = "qt_orgao_decisao_instancia") %>% 
  add_count(orgao, instancia, wt = qt_orgao_decisao_instancia,
            name = "qt_orgao_instancia") %>% 
  add_count(orgao, wt = qt_orgao_decisao_instancia,
            name = "qt_pedidos") 
```

```{r}
plot_correlacao_negativas_e_recursos <- function(df, decisao_pedido) {
  
  df <- df %>%
    group_by(orgao) %>% 
    mutate(
      qt_decisao = sum(if_else(
          decisao == decisao_pedido,
          qt_orgao_decisao_instancia,
          NA_integer_), 
        na.rm = T),
      qt_recurso = sum(if_else(
          !is.na(instancia),
          qt_orgao_decisao_instancia,
          NA_integer_),
        na.rm = T)
    ) %>% 
    ungroup() %>%
    filter(!is.na(instancia), decisao == decisao_pedido,
           instancia != "Pedido de Revisão") %>% 
    mutate(
      perc_decisao = qt_decisao / qt_pedidos,
      perc_recursos_quando_decisao = qt_orgao_decisao_instancia / qt_recurso
    ) %>% 
    group_by(instancia) %>% 
    mutate(correl = cor(perc_decisao, 
                        perc_recursos_quando_decisao)) %>% 
    ungroup()

  df %>% 
    ggplot(aes(x = perc_decisao,
               y = perc_recursos_quando_decisao,
               color = instancia,
               fill = instancia, size = qt_decisao)) +
    geom_point(shape = 21, alpha = .7, color = "gray50") +
    geom_smooth(method = "lm", se = F) +
    hrbrthemes::scale_y_percent() +
    hrbrthemes::scale_x_percent() +
    labs(
      title = str_glue("Correlação entre decisões de {tolower(decisao_pedido)}",
                       " e recursos"),
      subtitle = str_glue("O tamanho do ponto é proporcional à quantidade",
                          " de pedidos com decisao de {tolower(decisao_pedido)}"),
      x = str_glue("{decisao_pedido}\n(% do total de pedidos recebidos)"),
      y = str_glue("Recursos quando a decisão é {tolower(decisao_pedido)}\n",
                   "(% do total de recursos impetrados ao órgão)")
    ) +
    theme_minimal() +
    scale_color_manual(values = cores_instancia) +
    scale_fill_manual(values = cores_instancia) +
    theme(legend.position = "none",
          panel.background = element_rect(fill = "gray95", color = "transparent")) +
    facet_wrap(~ instancia)
  
}
```

### Acesso Negado

```{r fig.height=8}
plot_correlacao_negativas_e_recursos(count_recursos, "Acesso Negado") +
  geom_label(
    data = . %>% distinct(correl, instancia),
    aes(
      label = str_glue("Correlação:\n{round(correl, 3)}"),
      x = 0.1,
      y = 0.95
    ),
    alpha = .2,
    color = "gray30",
    size = 3,
    fontface = "bold"
  ) + 
  geom_text(
    data = . %>%
      filter(perc_recursos_quando_decisao >= .15 | perc_decisao > .3,
             !str_detect(orgao, "^COAF|^BB ")),
    aes(label = str_extract(orgao, "^[:upper:]+(?= )|^GSI-PR")),
    size = 2.5,
    fontface = "bold",
    color = "gray30",
    angle = 45,
    hjust = 0
  ) +
  geom_text(
    data = . %>%
      filter(perc_recursos_quando_decisao >= .25 & perc_decisao > .3),
    aes(label = str_extract(orgao, "^[:upper:]+(?= )|^GSI-PR")),
    size = 2.5,
    fontface = "bold",
    color = "gray30",
    hjust = 1,
    angle = 45
  )
```

### Acesso Concedido

```{r fig.height=8}
plot_correlacao_negativas_e_recursos(count_recursos, "Acesso Concedido") +
  geom_label(
    data = . %>% distinct(correl, instancia),
    aes(
      label = str_glue("Correlação:\n{round(correl, 3)}"),
      x = 0.25,
      y = 0.8
    ),
    alpha = .2,
    color = "gray30",
    size = 3,
    fontface = "bold"
  )
```

### Acesso Concedido

```{r fig.height=8}
plot_correlacao_negativas_e_recursos(count_recursos, 
                                     "Acesso Parcialmente Concedido") +
  geom_label(
    data = . %>% distinct(correl, instancia),
    aes(
      label = str_glue("Correlação:\n{round(correl, 3)}"),
      x = 0.05,
      y = 0.8
    ),
    alpha = .2,
    color = "gray30",
    size = 3,
    fontface = "bold"
  )
```

### Recursos e tipo de resposta para instâncias recursais

```{r fig.height=8, fig.width=10}
my_lbl <- function(x) scales::percent(x, accuracy = 1, decimal.mark = ",")
names(cores_tipo_resposta) <- names(cores_tipo_resposta) %>% str_wrap(15)

recursos_painel %>% 
  filter(instancia != "Pedido de Revisão", tipo_resposta != "Acolhimento") %>% 
  mutate(
    tipo_resposta = str_wrap(tipo_resposta, 15),
    tipo_resposta = ordered(tipo_resposta, levels = names(cores_tipo_resposta)),
    instancia = ordered(instancia, names(cores_instancia))
  ) %>% 
  group_by(id_pedido) %>%
  arrange(id_pedido, instancia) %>% 
  mutate(ord = 1:n()) %>% 
  ungroup() %>% 
  select(id_pedido,
         instancia,
         data_registro_recurso = data_registro, 
         tipo_resposta,
         ord) %>% 
  count(ano = year(data_registro_recurso), instancia, tipo_resposta,
        name = "n_recursos_ano_instancia_e_tipo_resposta") %>%
  complete(ano, 
           nesting(instancia, tipo_resposta), 
           fill = list(n_recursos_ano_instancia_e_tipo_resposta = 0)) %>% 
  add_count(ano, instancia,
            wt = n_recursos_ano_instancia_e_tipo_resposta,
            name = "n_recursos_ano_instancia") %>% 
  #filter(instancia == "Primeira Instância") %>% 
  mutate(per = n_recursos_ano_instancia_e_tipo_resposta / n_recursos_ano_instancia) %>% 
  ggplot(aes(
    x = ano,
    y = per,
    fill = tipo_resposta
  )) +
  geom_hline(yintercept = .5, lty = "dashed", color = "gray60") +
  geom_col(position = "dodge", color = "gray25") +
  geom_text(
    data = . %>% filter(ano == 2021, instancia == "Primeira Instância"),
    aes(label = my_lbl(per)),
    color = "gray20", fontface = "bold", size = 2.5, nudge_y = .05, nudge_x = 0.01
  ) +
  scale_x_continuous(breaks = 2012:2021, labels = glue("'{12:21}")) +
  scale_fill_manual(values = cores_tipo_resposta, guide = "none") +
  scale_color_manual(values = cores_tipo_resposta) +
  scale_y_percent(breaks = seq(0, 1, .25)) +
  facet_grid(instancia ~ tipo_resposta) +
  labs(x = "Ano",
       y = "% de recursos",
       fill = "Tipo de resposta", 
       title = "Tipo de resposta dada ao recurso",
       subtitle = "Como % do total de recursos em cada instância, por ano") +
  theme(strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "gray95", color = "transparent"))
```

## Motivo da abertura do recurso

Lista completa:

```{r, color-settings, eval=TRUE}
```

```{r fig.height=8}
recursos_painel %>%
  count(tipo_resposta,
        tipo_recurso = str_wrap(tipo_recurso, 40), sort = T) %>%
  na.omit() %>% 
  complete(tipo_resposta, tipo_recurso, fill = list(n = 0)) %>% 
  add_count(wt = n, name = "total_recursos") %>% 
  ggplot(aes(x = n / total_recursos, y = reorder(tipo_recurso, n),
             fill = reorder(tipo_resposta, n))) + 
  geom_col(position = "dodge") +
  scale_fill_manual(values = cores_tipo_resposta) +
  hrbrthemes::scale_x_percent() +
  labs(
    title = "Motivo da abertura do recurso",
    y = NULL,
    x = "Total de recursos (%)",
    fill = "Resposta do órgão:"
  )
```

6 principais motivos:

```{r fig.height=8}
top_6_motivos <- recursos_painel %>% 
  count(tipo_resposta,
        tipo_recurso = str_wrap(tipo_recurso, 40), sort = T,
        name = "n_resposta_motivo"
        ) %>%
  na.omit() %>% 
  add_count(wt = n_resposta_motivo, name = "n_recursos") %>%
  add_count(tipo_recurso, wt = n_resposta_motivo, name = "n_motivo") %>% 
  arrange(-n_motivo, n_resposta_motivo, tipo_resposta) %>% 
  group_by(tipo_recurso, n_motivo) %>% 
  nest() %>% 
  ungroup() %>% 
  mutate(rank_motivo = row_number()) %>% 
  unnest(everything()) %>% 
  filter(rank_motivo <= 6) 

top_6_motivos %>% 
  complete(
    tipo_resposta, 
    tipo_recurso, 
    fill = list(
      n_motivo = 0,
      n_resposta_motivo = 0,
      n_recursos = 0
  )) %>% 
  ggplot(aes(
    x = n_resposta_motivo / n_recursos,
    y = reorder(tipo_recurso,  n_resposta_motivo),
    fill = reorder(tipo_resposta, n_resposta_motivo)
  )) + 
  geom_col(position = "dodge") +
  scale_fill_manual(values = cores_tipo_resposta) +
  hrbrthemes::scale_x_percent() +
  labs(
    title = "Motivo da abertura do recurso",
    y = NULL,
    x = "Total de recursos (%)",
    fill = "Resposta do órgão:"
  )
```

```{r}
recursos_painel %>% 
  count(ano = year(data_registro),
        tipo_recurso = str_wrap(tipo_recurso, 40),
        name = "n_resposta_motivo") %>%
  add_count(ano, wt = n_resposta_motivo, name = "n_recursos") %>%
  add_count(ano, tipo_recurso, wt = n_resposta_motivo, name = "n_motivo") %>% 
  filter(tipo_recurso %in% unique(top_6_motivos$tipo_recurso)) %>% 
  ggplot(aes(x = ano, y = n_resposta_motivo / n_recursos, 
             color = reorder(tipo_recurso, -n_resposta_motivo),
             group = reorder(tipo_recurso, -n_resposta_motivo))) + 
  geom_line(size = 1) +
  geom_point() +
  scale_color_manual(values = cores_motivo_recurso) +
  #facet_wrap(~ reorder(tipo_recurso, -n_resposta_motivo)) +
  hrbrthemes::scale_y_percent() +
  labs(
    title = "Motivo da abertura do recurso - ano",
    color = "Motivo:",
    x = NULL,
    y = "Total de recursos (%)"
  ) +
  theme(
    legend.text = element_text(size = 8, margin = margin(5, 0, 5, 0, "pt"))
  )
```

