---
title: 'Negativas de acesso a informação no governo Federal'
subtitle: 'Órgãos e entidades do poder Executivo - janeiro de 2015 até 2021'
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_depth: 4
    theme: paper
    df_print: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = T,
  comment = "#>",
  message = F,
  warning = F,
  echo = T,
  fig.width = 8,
  fig.height = 5
)
```

```{r}
library(tidyverse)
library(lubridate)
library(glue)
library(here)
library(ggtext)
library(patchwork)
library(kableExtra)
library(hrbrthemes)

set.seed(1014)

knitr::knit_hooks$set(inline = function(x) prettyNum(x, big.mark = ".", decimal.mark = ","))

options(digits = 1,
        scipen = 999,
        OutDec = ",",
        knitr.kable.NA = '')

Sys.setenv(LANGUAGE = "pt-br")
Sys.setlocale("LC_TIME", "pt_BR")

# aplica identidade visual da TB/AeP:
aep_colors <- c(
  
  laranja = "#F9A521",
  rosa = "#D81755",
  cinza = "#969696",
  marrom = "#B27D5C"
  
)

paleta_governo = c(
  
  `Dilma II` = aep_colors[["laranja"]],
  `Temer` = aep_colors[["cinza"]],
  `Bolsonaro` = aep_colors[["rosa"]]  
  
)

tb_colors <- c(
  
  laranja = "#F6A323",
  cinza_escuro = "#1d1d1b",
  cinza_claro =  "#6f7171",
  cinza_quase_branco = "#ececec",
  azul = "#41ACBD"
  
  )

cores_decisao <- c(
  
  "Acesso Concedido" = tb_colors[["azul"]],
  "Não se trata de solicitação de informação" = aep_colors[["marrom"]],
  "Acesso Negado" = aep_colors[["rosa"]],
  "Acesso Parcialmente Concedido" = aep_colors[["laranja"]],
  "Pergunta Duplicada/Repetida" = aep_colors[["cinza"]],
  "Órgão não tem competência para responder sobre o assunto" = tb_colors[["cinza_escuro"]],
  "Informação Inexistente" = tb_colors[["cinza_quase_branco"]]

  )
```

```{r}
periodo_final <- "2021-08-01"
instancias_recursais <- c("Primeira Instância",
                          "Segunda Instância",
                          "Terceira Instância",
                          "CGU",
                          "CMRI",
                          "Pedido de Revisão",
                          "Não houve recurso")

pedidos_cgu <- readRDS(here("dados/load/rds/pedidos-clean.rds")) %>%
  filter(data_resposta <= periodo_final, data_resposta <= periodo_final)

recursos_cgu <- readRDS(here("dados/load/rds/recursos-clean.rds")) %>%
  filter(data_resposta <= periodo_final, data_resposta <= periodo_final) %>% 
  mutate(instancia = ordered(instancia, levels = instancias_recursais),
         instancia = fct_recode(instancia, "CGU" = "Terceira Instância")
         )

glimpse(pedidos_cgu)
glimpse(recursos_cgu)
```

## Recursos

```{r}
# filtra pedidos com recursos, na instância recursal em que ele finalizou:
recursos_por_id_instancia_e_decisao <- recursos_cgu %>% 
  filter(instancia != "Pedido de Revisão") %>% 
  group_by(id_pedido) %>%
  arrange(id_pedido, instancia) %>% 
  mutate(ord = 1:n()) %>% # ordenação por instancia recursal
  select(id_pedido, instancia, data_registro_recurso = data_registro, ord) %>% 
  ungroup()
```

```{r fig.height=3}
my_lbl <- function(x) scales::percent(x, accuracy = 0.01, decimal.mark = ",")

recursos_por_id_instancia_e_decisao %>%
  group_by(id_pedido) %>% 
  filter(ord == max(ord)) %>% 
  left_join(select(pedidos_cgu, id_pedido, data_registro_pedido = data_registro, decisao), .) %>% 
  mutate(instancia = fct_expand(instancia, "Não houve recurso"),
         instancia = replace_na(instancia, "Não houve recurso")) %>% 
  mutate(ano = year(data_registro_pedido)) %>% 
  count(ano, instancia, decisao,
        name = "n_recursos_ano_instancia_e_decisao")  %>% 
  mutate(houve_recurso = instancia == "Não houve recurso") %>%  
  count(ano, houve_recurso,
        wt = n_recursos_ano_instancia_e_decisao,
        name = "n_ano_houve_recurso") %>% 
  add_count(ano,
            wt = n_ano_houve_recurso,
            name = "n_ano") %>% 
  mutate(per = n_ano_houve_recurso / n_ano) %>% 
  ggplot(aes(x = ano, y = per, fill = houve_recurso, color = houve_recurso)) +
  geom_text(data = . %>% filter(houve_recurso), show.legend = F,
            aes(label = my_lbl(per)), nudge_y = .1, check_overlap = T) +
  geom_text(data = . %>% filter(!houve_recurso), show.legend = F,
            aes(label = my_lbl(per)), nudge_y = -.1, check_overlap = T) +
  geom_line(size = 2) +
  geom_point(size = 2.5, shape = 21, fill = "white") +
  scale_color_manual(values = c(tb_colors[["azul"]], aep_colors[["rosa"]]),
                     labels = c("Não houve recurso", "Houve recurso*"),
                     name = "% do total de pedidos") +
  scale_x_continuous(breaks = 2015:2021) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(title = "Pedidos que entraram com recurso",
       subtitle = "% do total de pedidos que entraram com recurso",
       x = NULL, y = NULL, caption = "*Pelo menos um recurso em 1ª instância")
```

</br></br>

```{r fig.height=8.5, fig.width=12}
cores_tipo_resposta <- c(
  tb_colors[["azul"]],
  alpha(tb_colors[["azul"]], .4),
  #tb_colors[["cinza_claro"]],
  alpha(tb_colors[["laranja"]], .25),
  alpha(tb_colors[["laranja"]], .6),
  tb_colors[["laranja"]],
  aep_colors[["rosa"]]
)

names(cores_tipo_resposta) <- c(
  "Deferido",
  "Parcialmente deferido",
  #"Acolhimento",
  "Perda de objeto parcial",
  "Perda de objeto",
  "Não conhecimento",
  "Indeferido"
) %>% str_wrap(15)

my_lbl <- function(x) scales::percent(x, accuracy = 1, decimal.mark = ",")

recursos_cgu %>% 
  filter(instancia != "Pedido de Revisão", tipo_resposta != "Acolhimento") %>% 
  mutate(
    tipo_resposta = str_wrap(tipo_resposta, 15),
    tipo_resposta = ordered(tipo_resposta, levels = names(cores_tipo_resposta))
  ) %>% 
  group_by(id_pedido) %>%
  arrange(id_pedido, instancia) %>% 
  mutate(ord = 1:n()) %>% 
  ungroup() %>% 
  select(id_pedido,
         instancia,
         data_registro_recurso = data_registro, 
         tipo_resposta,
         ord) %>% 
  count(ano = year(data_registro_recurso), instancia, tipo_resposta,
        name = "n_recursos_ano_instancia_e_tipo_resposta") %>%
  complete(ano, 
           nesting(instancia, tipo_resposta), 
           fill = list(n_recursos_ano_instancia_e_tipo_resposta = 0)) %>% 
  add_count(ano, instancia,
            wt = n_recursos_ano_instancia_e_tipo_resposta,
            name = "n_recursos_ano_instancia") %>% 
  #filter(instancia == "Primeira Instância") %>% 
  mutate(per = n_recursos_ano_instancia_e_tipo_resposta / n_recursos_ano_instancia) %>% 
  ggplot(aes(
    x = ano,
    y = per,
    fill = tipo_resposta
  )) +
  geom_hline(yintercept = .5, lty = "dashed", color = "gray60") +
  geom_col(position = "dodge", color = "gray25") +
  geom_text(
    data = . %>% filter(ano == 2021, instancia == "Primeira Instância"),
    aes(label = my_lbl(per)),
    color = "gray20", fontface = "bold", size = 2.5, nudge_y = .05, nudge_x = 0.01
  ) +
  scale_x_continuous(breaks = 2015:2021, labels = glue("'{15:21}")) +
  scale_fill_manual(values = cores_tipo_resposta) +
  scale_color_manual(values = cores_tipo_resposta) +
  scale_y_percent(limits = c(0, .8), breaks = seq(0, 1, .25)) +
  facet_grid(instancia ~ tipo_resposta) +
  labs(x = "Ano",
       y = "% de recursos",
       fill = "Tipo de resposta", 
       title = "Tipo de resposta dada ao recurso",
       subtitle = "Como % do total de recursos em cada instância, por ano") +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "gray95", color = "transparent"))
```


**Destaques**

- 50% das respostas dadas aos recursos em 1ª instância são Indeferidos ou de Não onhecimento 
- Redução de recursos Deferidos em 1º e 2º instância
- Aumento de recursos Indeferidos em 1º e 2º instância
- Quase todos os recursos em 3º (CGU) e 4º (CMRI) instância tem resposta Indeferida ou de Não conhecimento

</br></br>

```{r}
recursos_1a_instancia <- recursos_cgu %>%
  filter(instancia == "Primeira Instância") %>% 
  select(id_pedido,
         protocolo_pedido,
         id_recurso_1a_instancia = id_recurso,
         tipo_resposta_1a_instancia = tipo_resposta)

recursos_2a_instancia <- recursos_cgu %>%
  filter(instancia == "Segunda Instância") %>% 
  select(id_pedido,
         protocolo_pedido,
         id_recurso_2a_instancia = id_recurso,
         tipo_resposta_2a_instancia = tipo_resposta)

recursos_3a_instancia <- recursos_cgu %>%
  filter(instancia == "CGU") %>% 
  select(id_pedido,
         protocolo_pedido,
         id_recurso_3a_instancia = id_recurso,
         tipo_resposta_3a_instancia = tipo_resposta)

recursos_4a_instancia <- recursos_cgu %>%
  filter(instancia == "CMRI") %>% 
  select(id_pedido,
         protocolo_pedido,
         id_recurso_4a_instancia = id_recurso,
         tipo_resposta_4a_instancia = tipo_resposta)

recursos_wide <- pedidos_cgu %>%
  select(id_ano_base, id_pedido, protocolo_pedido, decisao, especificacao_decisao) %>% 
  inner_join(recursos_1a_instancia) %>% 
  left_join(recursos_2a_instancia) %>% 
  left_join(recursos_3a_instancia) %>% 
  left_join(recursos_4a_instancia)
```

</br></br>

Após receber uma resposta do órgão público com a decisão 


```{r fig.height=8.5, fig.width=10}
`%notin%` <- function(x, y) !(x %in% y)

names(cores_tipo_resposta) <- c(
  "Deferido",
  "Parcialmente deferido",
  #"Acolhimento",
  "Perda de objeto parcial",
  "Perda de objeto",
  "Não conhecimento",
  "Indeferido"
) %>% str_wrap(15)

recursos_wide %>% 
  count(id_ano_base, decisao, tipo_resposta_1a_instancia) %>% 
  filter(decisao %notin% c(
    "Pergunta Duplicada/Repetida",
    "Não se trata de solicitação de informação"
  )) %>% 
  #filter(decisao == "Acesso Concedido") %>% 
  mutate(ano = str_remove(id_ano_base, "_") %>% as.integer) %>%
  add_count(ano, name = "n_recursos_ano", wt = n) %>% 
  mutate(per = n / n_recursos_ano,
         decisao = str_wrap(decisao, 5),
         tipo_resposta_1a_instancia = str_wrap(tipo_resposta_1a_instancia, 15),
         tipo_resposta_1a_instancia = ordered(tipo_resposta_1a_instancia,
                                              levels = names(cores_tipo_resposta))) %>% 
  ggplot(aes(x = ano,
             y = per, fill = tipo_resposta_1a_instancia)) +
  geom_col() +
  labs(x = NULL, y = "Recursos impetrados após a decisão sobre acesso",
       title = "% de deferimento de recursos 1º instância",
       fill = "") +
  scale_y_percent() +
  scale_x_continuous(breaks = 2015:2021, labels = glue("'{15:21}")) +
  scale_fill_manual(values = cores_tipo_resposta) +
  facet_grid(tipo_resposta_1a_instancia ~ decisao)
```

