---
title: 'Monitoramento da Lei de Acesso a informação'
output:
    html_document:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = T,
  comment = "#>",
  message = F,
  warning = F,
  fig.align = "center",
  echo = F
)
```

```{r}
library(tidyverse)
library(here)
library(xml2)

docs <- list.files(here("docs")) %>% 
  paste0("docs/", .)

get_tags_h <- function(x, xpath) {
  x %>% 
    here() %>% 
    read_html() %>% 
    xml_find_all(xpath = xpath) %>% 
    xml_text() %>% 
    as_tibble_col(column_name = "section_title") %>% 
    mutate(tag = str_remove_all(xpath, "[:punct:]"))
}

tags_h <- c("//h1", "//h2", "//h3") %>% 
  map_df(get_tags_h, x = docs[3]) %>% 
  group_by(tag) %>% 
  mutate(
    ord_h3 = if_else(tag == "h3", row_number(), NA_integer_),
    ord_h2 = if_else(tag == "h2", row_number(), NA_integer_),
    ord_h1 = if_else(tag == "h1", row_number(), NA_integer_)
  ) %>% 
  ungroup()
  

toc <- docs[3] %>% 
  here() %>% 
  read_html() %>% 
  xml_find_all("//h3") %>% 
  xml_parents() %>% 
  map_df(xml_attrs) %>% 
  filter(str_detect(class, "section level")) %>% 
  mutate(tag = str_replace(class, "section level", "h")) %>% 
  group_by(tag) %>% 
  mutate(
    ord_h3 = if_else(tag == "h3", row_number(), NA_integer_),
    ord_h2 = if_else(tag == "h2", row_number(), NA_integer_),
    ord_h1 = if_else(tag == "h1", row_number(), NA_integer_)
  ) %>% 
  ungroup() %>% 
  left_join(tags_h, .) %>% 
  mutate(
    id = if_else(is.na(id), docs[3], paste0(docs[3], "#", id)) %>% 
      str_replace("docs", "https://transparencia-brasil.github.io/negativas-acesso-informacao-Executivo-federal-2021-1")
  ) %>% 
  arrange(ord_h1, ord_h2, ord_h3)

criado_em <- here("dados/load/rds") %>% 
  list.files(pattern = "pedidos-cgu", full.names = T) %>%
  file.info() %>% 
  pull(ctime) %>%
  format.Date("%d.%b.%Y às %Hh.%mmin.%Ss")
```


- **Manifestações totais e pedidos de acesso por decisão**
  + [`r toc$section_title[2]`](`r toc$id[2]`)
    + [`r toc$section_title[3]`](`r toc$id[3]`)
    + [`r toc$section_title[4]`](`r toc$id[4]`)
    + [`r toc$section_title[5]`](`r toc$id[5]`)
    + [`r toc$section_title[6]`](`r toc$id[6]`)
    + [`r toc$section_title[7]`](`r toc$id[7]`)

---

**Última atualização:** `r criado_em`
